<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Mona_Logistics_LTD.Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Admin\" />
    <Folder Include="User\Implementations\Account\" />
    <Folder Include="User\Interfaces\Account\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mona-Logistics-LTD.Data.Common\Mona-Logistics-LTD.Data.Common.csproj" />
    <ProjectReference Include="..\Mona-Logistics-LTD.Data.Models\Mona-Logistics-LTD.Data.Models.csproj" />
    <ProjectReference Include="..\Mona-Logistics-LTD.Data\Mona-Logistics-LTD.Data.csproj" />
    <ProjectReference Include="..\Mona-Logistics-LTD.Web.ViewModels\Mona-Logistics-LTD.Web.ViewModels.csproj" />
  </ItemGroup>

</Project>
