name: Keep site awake

on:
  schedule:
       - cron: '*/10 * * * *'
  workflow_dispatch: 
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the site
        run: |
          curl -I https://mona-logistics-ltd.onrender.com